version: "v1.0"
name: Pipeline
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804

blocks:
  - name: "Test/Build/Release"
    task:
      secrets:
        - name: s2prod-gce

      jobs:
      - name: "Test"
        commands:
          - change-go-version 1.9
          - echo $GCE_CREDS | base64 --decode > gce-creds.json
          - curl -L https://gist.githubusercontent.com/shiroyasha/40552df9486fdd7673fbad5656bba423/raw/11180be8fbf220d56c50e93ffd3fc9884a3ecdfb/install-gcloud.sh | bash
          - checkout
          - "export GOPATH=~/go"
          - mkdir -p ~/go/src/github.com/renderedtext
          - mv ~/sem ~/go/src/github.com/renderedtext/sem
          - make gsutil.configure
          - make go.get
          - make test
          - make build
          - make release
          - 'if [ "$SEMAPHORE_GIT_BRANCH" = "edge" ]; then make release.edge; fi'
          - 'if [ "$SEMAPHORE_GIT_BRANCH" = "stable" ]; then make release.stable; fi'
          - 'if [ "$SEMAPHORE_GIT_BRANCH" = "stable" ]; then curl -X POST -H "Content-type: application/json" --data "{\"text\":\"Sem CLI: New stable release: $(git log -1 --pretty=%B | tr -d \"\n\")\"}" "https://hooks.slack.com/services/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"; fi'
